version: '3.5'

services:
  postgres:
    container_name: postgres5431
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: defaultdb
      PGDATA: /data/postgres
    ports:
      - "5431:5432"
    restart: unless-stopped


